"""The PDF document pipeline, end to end through the HTTP API.

Covers the required cases: upload, invalid file rejection, successful
extraction, extraction failure, own-document access, cross-patient access
denied, deletion, and a missing document.

Everything here goes through `/patients/me/documents`, which is also the
point: there is no patient id anywhere in these paths, so the only id a test
can tamper with is the document id -- and tampering with it is exactly what
`test_cross_patient_cannot_...` exercises.
"""

from bson import ObjectId

from app.config import settings
from tests.pdf_fixtures import blank_pdf, corrupt_pdf, oversized_pdf, text_pdf

LAB_REPORT = "Complete Blood Count\nHaemoglobin 14.2 g/dL\nPlatelets 250000 /uL"


def upload_file(client, headers, content, filename="report.pdf", mime="application/pdf", **fields):
    """POST a multipart upload the way the browser does."""
    return client.post(
        "/patients/me/documents",
        files={"file": (filename, content, mime)},
        data=fields,
        headers=headers,
    )


def stored_documents(db, patient_id):
    return list(db.medical_documents.find({"patient_id": patient_id}))


# =====================================================================
# upload + successful extraction
# =====================================================================


def test_upload_stores_the_file_and_extracts_its_text(client, patient, storage, db):
    content = text_pdf(LAB_REPORT)

    response = upload_file(
        client, patient["headers"],
        content,
        filename="cbc.pdf",
        title="CBC report",
        category="lab_report",
        document_date="2026-06-01",
    )

    assert response.status_code == 201, response.text
    body = response.json()

    # Metadata required by the spec.
    assert body["patient_id"] == patient["id"]
    assert body["original_filename"] == "cbc.pdf"
    assert body["title"] == "CBC report"
    assert body["category"] == "lab_report"
    assert body["document_date"] == "2026-06-01"
    assert body["mime_type"] == "application/pdf"
    assert body["size_bytes"] == len(content)
    assert body["uploaded_at"]

    # Extraction really ran, on the real bytes.
    assert body["extraction_status"] == "completed"
    assert body["page_count"] == 1
    assert "Haemoglobin 14.2 g/dL" in body["extracted_text"]
    assert body["character_count"] == len(body["extracted_text"])
    assert body["has_text"] is True
    assert body["extraction_error"] is None

    # ...and the file is on disk, under a name we generated.
    document = stored_documents(db, patient["id"])[0]
    assert storage.exists(document["storage_key"])
    assert storage.open(document["storage_key"]) == content


def test_the_stored_name_is_generated_never_taken_from_the_upload(
    client, patient, storage, db
):
    """A filename is attacker-controlled input. It must never decide where
    bytes land, and it must not survive as a path."""
    hostile = "../../etc/passwd.pdf"

    response = upload_file(client, patient["headers"], text_pdf(), filename=hostile)

    assert response.status_code == 201, response.text
    body = response.json()

    # Displayed to the human, reduced to its basename: every directory
    # component is dropped rather than escaped.
    assert body["original_filename"] == "passwd.pdf"

    document = stored_documents(db, patient["id"])[0]
    # The key is generated by us: flat, opaque, no separators.
    assert ".." not in document["storage_key"]
    assert "/" not in document["storage_key"]
    assert document["storage_key"] != hostile
    assert storage.exists(document["storage_key"])


def test_title_falls_back_to_the_filename_when_not_supplied(client, patient, storage):
    response = upload_file(
        client, patient["headers"], text_pdf(), filename="lipid_panel_june.pdf"
    )

    assert response.status_code == 201, response.text
    assert response.json()["title"] == "Lipid panel june"


def test_uploaded_files_are_listed_newest_first(client, patient, storage):
    first = upload_file(client, patient["headers"], text_pdf(), filename="older.pdf")
    second = upload_file(client, patient["headers"], text_pdf(), filename="newer.pdf")
    assert first.status_code == 201 and second.status_code == 201

    response = client.get("/patients/me/documents", headers=patient["headers"])

    assert response.status_code == 200, response.text
    body = response.json()
    assert body["total"] == 2
    assert {item["id"] for item in body["items"]} == {
        first.json()["id"],
        second.json()["id"],
    }
    times = [item["uploaded_at"] for item in body["items"]]
    assert times == sorted(times, reverse=True)

    # Lists are metadata: resending every document's text on each poll would
    # dominate the response.
    assert all("extracted_text" not in item for item in body["items"])


def test_an_empty_record_list_is_not_an_error(client, patient, storage):
    response = client.get("/patients/me/documents", headers=patient["headers"])

    assert response.status_code == 200, response.text
    assert response.json() == {"items": [], "total": 0}


# =====================================================================
# extraction outcomes that are not "completed"
# =====================================================================


def test_a_scanned_pdf_is_marked_as_needing_ocr_not_as_empty(
    client, patient, storage, db
):
    """The image-only case.

    The document opens and every page reads fine; there is simply no embedded
    text. The honest answer is a status saying so, with *no* text -- an empty
    string here would let a later screen present "this record says nothing"
    as a finding."""
    response = upload_file(client, patient["headers"], blank_pdf(), filename="scan.pdf")

    assert response.status_code == 201, response.text
    body = response.json()
    assert body["extraction_status"] == "needs_ocr"
    assert body["extracted_text"] is None
    assert body["character_count"] == 0
    assert body["has_text"] is False
    assert body["extraction_error"] is None
    assert body["page_count"] == 1

    # The file itself is untouched and still listed.
    detail = client.get(
        f"/patients/me/documents/{body['id']}", headers=patient["headers"]
    )
    assert detail.status_code == 200
    assert detail.json()["extraction_status"] == "needs_ocr"
    assert storage.exists(stored_documents(db, patient["id"])[0]["storage_key"])


def test_an_unreadable_pdf_fails_extraction_without_failing_the_upload(
    client, patient, storage, db
):
    """Extraction is the only step that parses untrusted content, and the one
    most likely to throw. It runs *after* the row exists precisely so this
    degrades the document instead of losing it."""
    response = upload_file(client, patient["headers"], corrupt_pdf(), filename="broken.pdf")

    assert response.status_code == 201, response.text
    body = response.json()
    assert body["extraction_status"] == "failed"
    assert body["extracted_text"] is None
    assert body["has_text"] is False
    # A sentence the patient can read, not a stack trace or pypdf internals.
    assert body["extraction_error"] == "The file could not be read as a PDF."
    assert "Traceback" not in body["extraction_error"]

    # The document survives: listed, openable, downloadable.
    document = stored_documents(db, patient["id"])[0]
    assert storage.exists(document["storage_key"])
    listing = client.get("/patients/me/documents", headers=patient["headers"])
    assert listing.json()["total"] == 1
    download = client.get(
        f"/patients/me/documents/{body['id']}/file", headers=patient["headers"]
    )
    assert download.status_code == 200
    assert download.content == corrupt_pdf()


# =====================================================================
# rejecting files that are not what they claim
# =====================================================================


def test_a_file_that_is_not_a_pdf_is_refused_by_type(client, patient, db):
    response = upload_file(
        client, patient["headers"], b"Dear doctor, see attached", filename="notes.txt",
        mime="text/plain",
    )

    assert response.status_code == 415, response.text
    assert response.json()["code"] == "UNSUPPORTED_FILE_TYPE"
    assert stored_documents(db, patient["id"]) == []
    assert client.get("/patients/me/documents", headers=patient["headers"]).json()[
        "total"
    ] == 0


def test_a_file_that_lies_about_its_type_is_refused_by_content(client, patient, db):
    """The MIME type and the extension are both asserted by the client.

    This one claims `application/pdf` and is called `.pdf`, and still must
    not be accepted -- the magic bytes are the check that decides."""
    response = upload_file(
        client, patient["headers"], b"this is not actually a pdf", filename="report.pdf"
    )

    assert response.status_code == 400, response.text
    assert response.json()["code"] == "INVALID_FILE_TYPE"
    assert stored_documents(db, patient["id"]) == []


def test_an_oversized_file_is_refused(client, patient, db):
    response = upload_file(
        client, patient["headers"], oversized_pdf(), filename="huge.pdf"
    )

    assert response.status_code == 413, response.text
    assert response.json()["code"] == "FILE_TOO_LARGE"
    assert f"{settings.max_upload_mb} MB" in response.json()["detail"]
    # Nothing was written, no matter how far the stream got.
    assert stored_documents(db, patient["id"]) == []


def test_an_upload_with_no_file_at_all_is_refused(client, patient):
    response = client.post(
        "/patients/me/documents", data={"category": "other"}, headers=patient["headers"]
    )

    assert response.status_code == 422, response.text
    assert response.json()["code"] == "VALIDATION_ERROR"


def test_an_empty_file_is_refused(client, patient, db):
    response = upload_file(client, patient["headers"], b"", filename="empty.pdf")

    assert response.status_code == 400, response.text
    assert response.json()["code"] == "INVALID_FILE_TYPE"
    assert stored_documents(db, patient["id"]) == []


def test_an_impossible_document_date_is_refused(client, patient, db):
    response = upload_file(
        client, patient["headers"], text_pdf(), document_date="2026-02-30"
    )

    assert response.status_code == 422, response.text
    assert response.json()["code"] == "VALIDATION_ERROR"
    assert stored_documents(db, patient["id"]) == []


def test_an_unknown_category_is_refused(client, patient, db):
    response = upload_file(
        client, patient["headers"], text_pdf(), category="x-ray-of-my-soul"
    )

    assert response.status_code == 422, response.text
    assert stored_documents(db, patient["id"]) == []


# =====================================================================
# reading one document
# =====================================================================


def test_a_patient_can_open_their_own_document(client, patient, storage):
    created = upload_file(
        client, patient["headers"], text_pdf(LAB_REPORT), filename="cbc.pdf"
    ).json()

    response = client.get(
        f"/patients/me/documents/{created['id']}", headers=patient["headers"]
    )

    assert response.status_code == 200, response.text
    body = response.json()
    assert body["id"] == created["id"]
    assert body["extraction_status"] == "completed"
    assert "Haemoglobin 14.2 g/dL" in body["extracted_text"]

    # Phase 4A. This used to assert `extracted_data == {}`, which recorded the
    # pre-Phase-4A state rather than a property worth keeping: the structured
    # pass is the point of this phase, so that assertion could only have held
    # if the feature did nothing. It is replaced with a stronger one that
    # pins the actual lab values, their units, and their source attribution --
    # and, just as importantly, pins the absence of a `flag`, because nothing
    # on this report marks any value as abnormal and the extractor must not
    # decide that for itself.
    extracted = body["extracted_data"]
    assert extracted["lab_values"] == [
        {
            "name": "Haemoglobin",
            "value": "14.2",
            "unit": "g/dL",
            "source_text": "Haemoglobin 14.2 g/dL",
        },
        {
            "name": "Platelets",
            "value": "250000",
            "unit": "/uL",
            "source_text": "Platelets 250000 /uL",
        },
    ]
    # No condition, finding, medication, or metadata was printed on this
    # report, so none may appear.
    for absent in (
        "stated_conditions",
        "abnormal_findings",
        "medications",
        "report_title",
        "document_date",
        "referring_facility",
        "referring_doctor",
    ):
        assert absent not in extracted, f"{absent} was not stated on this report"


def test_the_original_file_streams_back_byte_for_byte(client, patient, storage, db):
    content = text_pdf(LAB_REPORT)
    created = upload_file(client, patient["headers"], content, filename="cbc.pdf").json()

    response = client.get(
        f"/patients/me/documents/{created['id']}/file", headers=patient["headers"]
    )

    assert response.status_code == 200, response.text
    assert response.headers["content-type"].startswith("application/pdf")
    assert response.content == content
    # Never cached off the device: this is the record itself.
    assert "no-store" in response.headers["cache-control"]
    assert "attachment" not in response.headers["content-disposition"]


def test_a_missing_document_returns_404(client, patient, storage):
    # A well-formed id that simply does not exist.
    absent = "64b000000000000000000000"

    detail = client.get(
        f"/patients/me/documents/{absent}", headers=patient["headers"]
    )
    download = client.get(
        f"/patients/me/documents/{absent}/file", headers=patient["headers"]
    )
    removal = client.delete(
        f"/patients/me/documents/{absent}", headers=patient["headers"]
    )

    for response in (detail, download, removal):
        assert response.status_code == 404, response.text
        assert response.json()["code"] == "DOCUMENT_NOT_FOUND"


def test_a_malformed_document_id_returns_404_not_a_500(client, patient, storage):
    # Neither of these is a valid ObjectId, so neither can reach Mongo as a
    # failed cast -- the service rejects them before the query runs.
    for bad in ("not-an-id", "zzzzzzzzzzzzzzzzzzzzzzzzzz"):
        response = client.get(
            f"/patients/me/documents/{bad}", headers=patient["headers"]
        )
        assert response.status_code == 404, (bad, response.text)
        assert response.json()["code"] == "DOCUMENT_NOT_FOUND"


# =====================================================================
# cross-patient access: the security property
# =====================================================================


def test_another_patient_cannot_read_your_document(
    client, patient, other_patient, storage
):
    """Change the id in the request and nothing happens.

    404 rather than 403, deliberately: 403 would confirm that a document with
    that id exists, turning this endpoint into an oracle for guessing other
    patients' document ids."""
    created = upload_file(client, patient["headers"], text_pdf(LAB_REPORT)).json()

    response = client.get(
        f"/patients/me/documents/{created['id']}", headers=other_patient["headers"]
    )

    assert response.status_code == 404, response.text
    assert response.json()["code"] == "DOCUMENT_NOT_FOUND"
    # ...and no detail from the real document leaks through.
    assert "Haemoglobin" not in response.text


def test_another_patient_cannot_download_your_file(
    client, patient, other_patient, storage
):
    created = upload_file(client, patient["headers"], text_pdf(LAB_REPORT)).json()

    response = client.get(
        f"/patients/me/documents/{created['id']}/file",
        headers=other_patient["headers"],
    )

    assert response.status_code == 404, response.text
    assert response.content != text_pdf(LAB_REPORT)


def test_another_patient_cannot_delete_your_document(
    client, patient, other_patient, storage, db
):
    created = upload_file(client, patient["headers"], text_pdf(LAB_REPORT)).json()

    response = client.delete(
        f"/patients/me/documents/{created['id']}", headers=other_patient["headers"]
    )

    assert response.status_code == 404, response.text

    # Neither the row nor the file was touched.
    assert client.get(
        f"/patients/me/documents/{created['id']}", headers=patient["headers"]
    ).status_code == 200
    document = stored_documents(db, patient["id"])[0]
    assert storage.exists(document["storage_key"])


def test_each_patient_sees_only_their_own_list(
    client, patient, other_patient, storage
):
    mine = upload_file(client, patient["headers"], text_pdf(), filename="mine.pdf").json()
    theirs = upload_file(
        client, other_patient["headers"], text_pdf(), filename="theirs.pdf"
    ).json()

    my_list = client.get("/patients/me/documents", headers=patient["headers"]).json()
    their_list = client.get(
        "/patients/me/documents", headers=other_patient["headers"]
    ).json()

    assert [item["id"] for item in my_list["items"]] == [mine["id"]]
    assert [item["id"] for item in their_list["items"]] == [theirs["id"]]
    assert my_list["items"][0]["patient_id"] == patient["id"]
    assert their_list["items"][0]["patient_id"] == other_patient["id"]


def test_tampering_with_the_patient_id_field_changes_nothing(
    client, patient, other_patient, storage, db
):
    """Even a document row's own `patient_id` is not something a caller can
    steer: every read is scoped by the id taken from the token, so the field
    in the request is never consulted."""
    created = upload_file(client, patient["headers"], text_pdf(), filename="mine.pdf").json()

    # Rewrite the stored document to claim the other patient owns it.
    db.medical_documents.update_one(
        {"_id": ObjectId(created["id"])},
        {"$set": {"patient_id": other_patient["id"]}},
    )

    # The original owner can no longer see it...
    assert (
        client.get(
            f"/patients/me/documents/{created['id']}", headers=patient["headers"]
        ).status_code
        == 404
    )
    # ...and the person it now claims to belong to can, because ownership is
    # read from the row and compared against the token -- not from anything
    # in the request body.
    assert (
        client.get(
            f"/patients/me/documents/{created['id']}",
            headers=other_patient["headers"],
        ).status_code
        == 200
    )


# =====================================================================
# deletion
# =====================================================================


def test_deleting_removes_both_the_row_and_the_file(
    client, patient, storage, db
):
    created = upload_file(client, patient["headers"], text_pdf(LAB_REPORT)).json()
    document = stored_documents(db, patient["id"])[0]
    assert storage.exists(document["storage_key"])

    response = client.delete(
        f"/patients/me/documents/{created['id']}", headers=patient["headers"]
    )

    assert response.status_code == 200, response.text
    assert response.json()["code"] == "DOCUMENT_DELETED"

    assert db.medical_documents.find_one({"_id": ObjectId(created["id"])}) is None
    assert not storage.exists(document["storage_key"])
    assert client.get("/patients/me/documents", headers=patient["headers"]).json()[
        "total"
    ] == 0


def test_deleting_twice_is_a_404_not_a_crash(client, patient, storage):
    created = upload_file(client, patient["headers"], text_pdf()).json()

    first = client.delete(
        f"/patients/me/documents/{created['id']}", headers=patient["headers"]
    )
    second = client.delete(
        f"/patients/me/documents/{created['id']}", headers=patient["headers"]
    )

    assert first.status_code == 200
    assert second.status_code == 404
    assert second.json()["code"] == "DOCUMENT_NOT_FOUND"


# =====================================================================
# authorization on the routes themselves
# =====================================================================


def test_an_upload_requires_a_token(client, db):
    response = client.post(
        "/patients/me/documents",
        files={"file": ("report.pdf", text_pdf(), "application/pdf")},
    )

    assert response.status_code == 401, response.text
    assert db.medical_documents.count_documents({}) == 0


def test_a_doctor_cannot_use_the_patient_document_routes(client, doctor, storage):
    """Being a doctor is not authorization. Nothing in this phase shares a
    record with a doctor; that needs an explicit grant, which is Phase 3."""
    listing = client.get("/patients/me/documents", headers=doctor["headers"])
    upload_attempt = upload_file(client, doctor["headers"], text_pdf())

    for response in (listing, upload_attempt):
        assert response.status_code == 403, response.text
        assert response.json()["code"] == "ROLE_NOT_ALLOWED"


def test_a_token_from_a_deleted_account_is_refused(
    client, patient, storage, db
):
    upload_file(client, patient["headers"], text_pdf())
    db.users.delete_one({"_id": ObjectId(patient["id"])})

    response = client.get("/patients/me/documents", headers=patient["headers"])

    assert response.status_code == 401
    assert response.json()["code"] == "USER_NOT_FOUND"
